### PR TITLE
Let's go dynamic!

### PR DESCRIPTION
**Pull request by fexra**
- Express.Js
- Pug
- Helmet 
- Compression / Cache

### CODE REVIEW

**Comment by brandonlehmann** [comment]
I want planning on this being a NPM package. 

Back in the day, sites like this used to be hosted just fine on <insert httpd package of choice>. A front end should be a front end. All the backend magic works via the API. The caching of the data lives in the CDN. 

I’m afraid that accepting what you’ve done here merges front and backend again.

**Comment by fexra** [comment]
I understand your reasoning., I will continue this as a separate project for the NPM lovers :)

**Comment by brandonlehmann** [comment]
@fexra You do know you have permission to create it as a separate repo in the org... right lol?

**Comment by fexra** [comment]
> @fexra You do know you have permission to create it as a separate repo in the org... right lol?

no permission

**Pull request closed without merging**
